jobs:
- language: rust
  rust:
    - stable
- language: rust
  rust:
    - stable
  services:
    - docker
  before_install:
    - docker pull clux/muslrust
  script:
    # Build static executable before script (the script will build the crate)
    - docker run -v cargo-cache:/root/.cargo/registry -v $PWD:/volume --rm -t clux/muslrust cargo build --release
  deploy:
    - provider: releases
      file:
        - "target/x86_64-unknown-linux-musl/release/rmesg"
      on:
        tags: true
      edge: true
