services:
  - docker
before_install:
  - docker pull polyverse/rust-dev-env
script:
  - docker run -v cargo-cache:/root/.cargo/registry -v $PWD:/volume --rm -t polyverse/rust-dev-env cargo clippy --all-targets
  - docker run -v cargo-cache:/root/.cargo/registry -v $PWD:/volume --rm -t polyverse/rust-dev-env cargo clippy --all-targets --features="async"
  - docker run -v cargo-cache:/root/.cargo/registry -v $PWD:/volume --rm -t polyverse/rust-dev-env cargo clippy --all-targets --features="ptr"
  - docker run -v cargo-cache:/root/.cargo/registry -v $PWD:/volume --rm -t polyverse/rust-dev-env cargo clippy --all-targets --features="async ptr"
  # Test with cartesian product of features: async on/off and ptr on/off
  - docker run -v cargo-cache:/root/.cargo/registry -v $PWD:/volume --rm -t --privileged polyverse/rust-dev-env cargo test --all-targets
  - docker run -v cargo-cache:/root/.cargo/registry -v $PWD:/volume --rm -t --privileged polyverse/rust-dev-env cargo test --all-targets --features="async"
  - docker run -v cargo-cache:/root/.cargo/registry -v $PWD:/volume --rm -t --privileged polyverse/rust-dev-env cargo test --all-targets --features="ptr"
  - docker run -v cargo-cache:/root/.cargo/registry -v $PWD:/volume --rm -t --privileged polyverse/rust-dev-env cargo test --all-targets --features="async ptr"

  # Build static executable with the Async feature (and not pointer feature)
  - docker run -v cargo-cache:/root/.cargo/registry -v $PWD:/volume --rm -t polyverse/rust-dev-env cargo build --release --all-targets --features="async ptr"
deploy:
  - provider: releases
    file:
      - "target/x86_64-unknown-linux-musl/release/rmesg"
    on:
      tags: true
    edge: true
