[package]
name = "rmesg"
version = "0.1.1"
authors = ["Archis Gore <archis@polyverse.com>"]
edition = "2018"
license-file = "LICENSE"
categories = ["os", "command-line-utilities"]
keywords = ["dmesg", "klogctl", "printk", "syslog"]
readme = "README.md"
repository = "https://github.com/polyverse/rmesg"
travis-ci = { repository = "polyverse/rmesg", branch = "master" }

description = """This is a fully Rust-based implementation of the popular dmesg Linux utility, giving
 programmatic access to the kernel log buffer."""

[dependencies]
libc = "0.2.69"
cfg-if = "0.1.10"
