name: Build Status

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    strategy:
      matrix:
        operation: ["clippy", "test"]
        # Features available in the crate
        featsync: ["", "async"]
        feattrait: ["", "extra-traits"]
        featptr: ["", "ptr"]
    steps:
      - uses: actions/checkout@v2

      - name: ${{matrix.operation}} ${{matrix.featsync}} ${{matrix.feattrait}} ${{matrix.featptr}}
        run: docker run -v cargo-cache:/root/.cargo/registry -v $PWD:/volume --privileged --rm -t ghcr.io/polyverse/rust-dev-env/rust-dev-env:latest cargo ${{matrix.operation}} --all --features="${{matrix.featsync}} ${{matrix.feattrait}} ${{matrix.featptr}}"
